# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: charles22
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-cicd

provider:
  name: aws
  runtime: python3.12

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
